import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/toast-provider";
import ThemeManager from "@/components/ThemeManager";
// 1. ADIM: Context'i içe aktar
import { SearchProvider } from "@/context/SearchContext"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--background)] text-[var(--foreground)]`}
      >
        {/* 2. ADIM: Tüm uygulamayı (Provider, Manager ve Children) kapsayacak şekilde sarmala */}
        <SearchProvider>
            <ThemeManager />
            <ToastProvider />
            {children}
        </SearchProvider>
      </body>
    </html>
  );
}