// utils/locations.ts

export type LocationType = 'city' | 'country' | 'venue' | 'district';

export interface LocationItem {
  name: string;
  type: LocationType;
  detail?: string;
}

// ---------------------------------------------------------------------------
// PERFORMANS NOTU: Bu liste bileşen dışında olduğu için render bloklamaz.
// ---------------------------------------------------------------------------

export const ALL_LOCATIONS: LocationItem[] = [
  // --- ÜLKELER (Önemli olanlar en başta) ---
  { name: "Türkiye", type: "country" },
  { name: "Amerika Birleşik Devletleri", type: "country" },
  { name: "Almanya", type: "country" },
  { name: "İngiltere", type: "country" },
  { name: "Fransa", type: "country" },
  { name: "İtalya", type: "country" },
  { name: "Hollanda", type: "country" },
  { name: "Azerbaycan", type: "country" },
  { name: "KKTC", type: "country" },

  // --- TÜRKİYE'NİN 81 İLİ ---
  { name: "Adana", type: "city", detail: "Türkiye" },
  { name: "Adıyaman", type: "city", detail: "Türkiye" },
  { name: "Afyonkarahisar", type: "city", detail: "Türkiye" },
  { name: "Ağrı", type: "city", detail: "Türkiye" },
  { name: "Aksaray", type: "city", detail: "Türkiye" },
  { name: "Amasya", type: "city", detail: "Türkiye" },
  { name: "Ankara", type: "city", detail: "Türkiye" },
  { name: "Antalya", type: "city", detail: "Türkiye" },
  { name: "Ardahan", type: "city", detail: "Türkiye" },
  { name: "Artvin", type: "city", detail: "Türkiye" },
  { name: "Aydın", type: "city", detail: "Türkiye" },
  { name: "Balıkesir", type: "city", detail: "Türkiye" },
  { name: "Bartın", type: "city", detail: "Türkiye" },
  { name: "Batman", type: "city", detail: "Türkiye" },
  { name: "Bayburt", type: "city", detail: "Türkiye" },
  { name: "Bilecik", type: "city", detail: "Türkiye" },
  { name: "Bingöl", type: "city", detail: "Türkiye" },
  { name: "Bitlis", type: "city", detail: "Türkiye" },
  { name: "Bolu", type: "city", detail: "Türkiye" },
  { name: "Burdur", type: "city", detail: "Türkiye" },
  { name: "Bursa", type: "city", detail: "Türkiye" },
  { name: "Çanakkale", type: "city", detail: "Türkiye" },
  { name: "Çankırı", type: "city", detail: "Türkiye" },
  { name: "Çorum", type: "city", detail: "Türkiye" },
  { name: "Denizli", type: "city", detail: "Türkiye" },
  { name: "Diyarbakır", type: "city", detail: "Türkiye" },
  { name: "Düzce", type: "city", detail: "Türkiye" },
  { name: "Edirne", type: "city", detail: "Türkiye" },
  { name: "Elazığ", type: "city", detail: "Türkiye" },
  { name: "Erzincan", type: "city", detail: "Türkiye" },
  { name: "Erzurum", type: "city", detail: "Türkiye" },
  { name: "Eskişehir", type: "city", detail: "Türkiye" },
  { name: "Gaziantep", type: "city", detail: "Türkiye" },
  { name: "Giresun", type: "city", detail: "Türkiye" },
  { name: "Gümüşhane", type: "city", detail: "Türkiye" },
  { name: "Hakkari", type: "city", detail: "Türkiye" },
  { name: "Hatay", type: "city", detail: "Türkiye" },
  { name: "Iğdır", type: "city", detail: "Türkiye" },
  { name: "Isparta", type: "city", detail: "Türkiye" },
  { name: "İstanbul", type: "city", detail: "Türkiye" },
  { name: "İzmir", type: "city", detail: "Türkiye" },
  { name: "Kahramanmaraş", type: "city", detail: "Türkiye" },
  { name: "Karabük", type: "city", detail: "Türkiye" },
  { name: "Karaman", type: "city", detail: "Türkiye" },
  { name: "Kars", type: "city", detail: "Türkiye" },
  { name: "Kastamonu", type: "city", detail: "Türkiye" },
  { name: "Kayseri", type: "city", detail: "Türkiye" },
  { name: "Kırıkkale", type: "city", detail: "Türkiye" },
  { name: "Kırklareli", type: "city", detail: "Türkiye" },
  { name: "Kırşehir", type: "city", detail: "Türkiye" },
  { name: "Kilis", type: "city", detail: "Türkiye" },
  { name: "Kocaeli", type: "city", detail: "Türkiye" },
  { name: "Konya", type: "city", detail: "Türkiye" },
  { name: "Kütahya", type: "city", detail: "Türkiye" },
  { name: "Malatya", type: "city", detail: "Türkiye" },
  { name: "Manisa", type: "city", detail: "Türkiye" },
  { name: "Mardin", type: "city", detail: "Türkiye" },
  { name: "Mersin", type: "city", detail: "Türkiye" },
  { name: "Muğla", type: "city", detail: "Türkiye" },
  { name: "Muş", type: "city", detail: "Türkiye" },
  { name: "Nevşehir", type: "city", detail: "Türkiye" },
  { name: "Niğde", type: "city", detail: "Türkiye" },
  { name: "Ordu", type: "city", detail: "Türkiye" },
  { name: "Osmaniye", type: "city", detail: "Türkiye" },
  { name: "Rize", type: "city", detail: "Türkiye" },
  { name: "Sakarya", type: "city", detail: "Türkiye" },
  { name: "Samsun", type: "city", detail: "Türkiye" },
  { name: "Siirt", type: "city", detail: "Türkiye" },
  { name: "Sinop", type: "city", detail: "Türkiye" },
  { name: "Sivas", type: "city", detail: "Türkiye" },
  { name: "Şanlıurfa", type: "city", detail: "Türkiye" },
  { name: "Şırnak", type: "city", detail: "Türkiye" },
  { name: "Tekirdağ", type: "city", detail: "Türkiye" },
  { name: "Tokat", type: "city", detail: "Türkiye" },
  { name: "Trabzon", type: "city", detail: "Türkiye" },
  { name: "Tunceli", type: "city", detail: "Türkiye" },
  { name: "Uşak", type: "city", detail: "Türkiye" },
  { name: "Van", type: "city", detail: "Türkiye" },
  { name: "Yalova", type: "city", detail: "Türkiye" },
  { name: "Yozgat", type: "city", detail: "Türkiye" },
  { name: "Zonguldak", type: "city", detail: "Türkiye" },

  // --- İSTANBUL İLÇELERİ (Örnek) ---
  { name: "Kadıköy", type: "district", detail: "İstanbul" },
  { name: "Beşiktaş", type: "district", detail: "İstanbul" },
  { name: "Şişli", type: "district", detail: "İstanbul" },
  { name: "Üsküdar", type: "district", detail: "İstanbul" },
  { name: "Bakırköy", type: "district", detail: "İstanbul" },
  { name: "Fatih", type: "district", detail: "İstanbul" },
  { name: "Beyoğlu", type: "district", detail: "İstanbul" },
  { name: "Sarıyer", type: "district", detail: "İstanbul" },
  { name: "Kartal", type: "district", detail: "İstanbul" },
  { name: "Maltepe", type: "district", detail: "İstanbul" },
  { name: "Pendik", type: "district", detail: "İstanbul" },
  { name: "Ataşehir", type: "district", detail: "İstanbul" },
  { name: "Beykoz", type: "district", detail: "İstanbul" },
  { name: "Çekmeköy", type: "district", detail: "İstanbul" },
  { name: "Tuzla", type: "district", detail: "İstanbul" },
  { name: "Ümraniye", type: "district", detail: "İstanbul" },
  { name: "Zeytinburnu", type: "district", detail: "İstanbul" },
  { name: "Eyüpsultan", type: "district", detail: "İstanbul" },
  { name: "Kağıthane", type: "district", detail: "İstanbul" },
  
  // --- ANKARA İLÇELERİ ---
  { name: "Çankaya", type: "district", detail: "Ankara" },
  { name: "Keçiören", type: "district", detail: "Ankara" },
  { name: "Yenimahalle", type: "district", detail: "Ankara" },
  { name: "Mamak", type: "district", detail: "Ankara" },
  { name: "Etimesgut", type: "district", detail: "Ankara" },
  { name: "Sincan", type: "district", detail: "Ankara" },
  { name: "Gölbaşı", type: "district", detail: "Ankara" },
  
  // --- İZMİR İLÇELERİ ---
  { name: "Konak", type: "district", detail: "İzmir" },
  { name: "Karşıyaka", type: "district", detail: "İzmir" },
  { name: "Bornova", type: "district", detail: "İzmir" },
  { name: "Buca", type: "district", detail: "İzmir" },
  { name: "Çiğli", type: "district", detail: "İzmir" },
  { name: "Bayraklı", type: "district", detail: "İzmir" },
  { name: "Balçova", type: "district", detail: "İzmir" },
  { name: "Urla", type: "district", detail: "İzmir" },
  { name: "Çeşme", type: "district", detail: "İzmir" },

  // --- ADLİYELER (Venue) ---
  { name: "Çağlayan Adliyesi", type: "venue", detail: "İstanbul" },
  { name: "Kartal Adliyesi", type: "venue", detail: "İstanbul" },
  { name: "Bakırköy Adliyesi", type: "venue", detail: "İstanbul" },
  { name: "Ankara Adliyesi", type: "venue", detail: "Sıhhiye" },
  { name: "İzmir Adliyesi", type: "venue", detail: "Bayraklı" },
  { name: "Yargıtay Başkanlığı", type: "venue", detail: "Ankara" },
  { name: "Danıştay Başkanlığı", type: "venue", detail: "Ankara" },
  { name: "Anayasa Mahkemesi", type: "venue", detail: "Ankara" },

  // --- DÜNYA ŞEHİRLERİ (Major) ---
  { name: "London", type: "city", detail: "United Kingdom" },
  { name: "New York", type: "city", detail: "USA" },
  { name: "Berlin", type: "city", detail: "Germany" },
  { name: "Paris", type: "city", detail: "France" },
  { name: "Tokyo", type: "city", detail: "Japan" },
  { name: "Dubai", type: "city", detail: "UAE" },
  { name: "Moscow", type: "city", detail: "Russia" },
  { name: "Los Angeles", type: "city", detail: "USA" },
  { name: "Barcelona", type: "city", detail: "Spain" },
  { name: "Rome", type: "city", detail: "Italy" },
  { name: "Amsterdam", type: "city", detail: "Netherlands" },
  { name: "Brussels", type: "city", detail: "Belgium" },
  { name: "Vienna", type: "city", detail: "Austria" },
  { name: "Kyiv", type: "city", detail: "Ukraine" },
  { name: "Baku", type: "city", detail: "Azerbaijan" },
  // ... (Burayı istediğin kadar uzatabilirsin, 10.000 satır olsa bile sorun olmaz)
];